basic_config_default: &basic_config_default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  
default: &default
  <<: *basic_config_default
  host: 127.0.0.1
  username: mvp
  password: secret

development:
  <<: *default
  database: prototype_develop
